window.MINISTERIO_SEED_GROUPS = [
  {
    producer: "elite",
    source: "Acervo Elite",
    tracks: [
      "4 por 1 - Cinco Pães e Dois Peixinhos",
      "4 por 1 - Diante de Ti",
      "4 por 1 - Diante de Ti (Arranjo Elite)",
      "4 por 1 - Espírito Enche Minha Vida",
      "4 por 1 - Um Chamado",
      "Abertura Elite 3.0",
      "Adhemar de Campos - Grande é o Senhor",
      "Adhemar de Campos - Louvemos ao Senhor",
      "Alexsander Lúcio - Buscar-me-Eis e Me Achareis",
      "Alexsander Lúcio - O Fogo Arderá",
      "Aline Barros (Sem Backs) - Tudo é Teu",
      "Aline Barros + Sarah Beatriz - A Promessa Nasceu",
      "Aline Barros - Ao Erguermos As Mãos",
      "Aline Barros - Ao Único",
      "Aline Barros - Apaixonado",
      "Aline Barros - Autor da Vida",
      "Aline Barros - Bem Aventurado",
      "Aline Barros - Bem Mais Que Tudo",
      "Aline Barros - Consagração",
      "Aline Barros - Depois da Cruz",
      "Aline Barros - Diante da Cruz",
      "Aline Barros - Digno é o Senhor",
      "Aline Barros - Esperança",
      "Aline Barros - Eternidade + Imensurável",
      "Aline Barros - Imensurável",
      "Aline Barros - Jeová Jireh",
      "Aline Barros - Lugar Seguro",
      "Aline Barros - Medley Fico Feliz + Feliz Demais",
      "Aline Barros - Medley O Espírito de Deus Está Aqui",
      "Aline Barros - Não Há Deus Maior",
      "Aline Barros - Poder do Teu Amor",
      "Aline Barros - Poder Pra Salvar",
      "Aline Barros - Primeira Essência",
      "Aline Barros - Rei Meu",
      "Aline Barros - Rendido Estou",
      "Aline Barros - Ressuscita-me",
      "Aline Barros - Ressuscita-me 30 Anos",
      "Aline Barros - Sonda-me, Usa-me",
      "Aline Barros - Te Adorar é o Meu Prazer",
      "Aline Barros - Tua Palavra",
      "Aline Barros - Tudo Diferente",
      "Aline Barros - Tudo é Teu",
      "Aline Barros - Vitória No Deserto",
      "Aline Barros - Vou Te Alegrar",
      "Aline Silva - Em Nome de Jesus",
      "Alisson e Neide - Paulo e Silas",
      "Ana Nóbrega - Quando Ele Vem",
      "Anderson Freire - Efésios 6",
      "Anderson Freire - Medley",
      "Anderson Freire - Raridade",
      "André Valadão - Milagre",
      "André Valadão - Pela Fé",
      "Anna Clara Rocha - Fogo em Teus Olhos",
      "Antônio Cirilo - Poderoso Deus",
      "Attos 2 - Escape",
      "Attos 2 - Na Unção de Deus",
      "Banda Som e Louvor - Medley 500 Graus",
      "Be One Music - Rei do Meu Coração",
      "Bethel Music - Agnus Day",
      "Bruna Karla - Advogado Fiel",
      "Bruna Karla - Quando Eu Chorar",
      "Canção e Louvor - Rei e Santo",
      "Cantares - Maravilhoso És",
      "Cassiane + Gabriel Guedes - Com Muito Louvor",
      "Cassiane - Amigo Espírito Santo",
      "Cassiane - Grandes Sucessos",
      "Cassiane - Hino da Vitória",
      "Cassiane - O Leão e o Cordeiro",
      "Central 3 - Tudo a Ver Com Ele",
      "Cia SALT - Eu Quero Conhecer Jesus",
      "Comunhão e Adoração 4 - Comunhão e Adoração",
      "Comunhão e Adoração - Nuvem de Glória",
      "Comuni. Evangélica de Maringá - Descansarei",
      "Comunidade de Nilópolis - Cria Em Mim",
      "Comunidade de Nilópolis - Deus Sara Esta Nação",
      "Comunidade Zona Sul - Rompendo em Fé",
      "Damares - Consolador",
      "Daniel - Até Que Eu Não Consiga Mais Ficar de Pé",
      "Danielle Cristina - Fidelidade",
      "Davi Fernandes - Até Que o Senhor Venha",
      "Davi Sacer - Desejo do Meu Coração",
      "Davi Sacer - Deus de Promessas",
      "Davi Sacer - Deus Não Falhará",
      "Davi Sacer - Sete Vezes Mais",
      "Davi Sacer - Tua Graça Me Basta",
      "Davi Sacer - Venha o Teu Reino",
      "David Quinlan - Abra os Olhos do Meu Coração",
      "David Quinlan - Abraça-me",
      "David Quinlan - Agnus Dei",
      "David Quinlan - Águas Profundas",
      "David Quinlan - Essência da Adoração",
      "Deigma Marques - Que Ele Cresça",
      "Delino Marçal - Deus é Deus",
      "Delino Marçal - Vim Falar Com Deus",
      "Delino Marçal - Você Não Imagina",
      "Diante do Trono - Me Ama",
      "Diante do Trono - Medley Coração Igual ao Teu",
      "Diante do Trono - Medley Relance",
      "Diante do Trono - Medley Te Agradeço",
      "Diante do Trono - Nos Braços do Pai",
      "Diante do Trono - Preciso de Ti",
      "Diante do Trono - Tempo de Festa",
      "Discopraise - Ouvir o Teu Falar",
      "Discopraise - Se Eu Me Humilhar",
      "Drops - É Ele",
      "Drops - Grato Sou",
      "Drops - Maravilhosa Graça",
      "Drops - Tudo é Teu",
      "Dunamis Music - Estações",
      "Elaine de Jesus - Na Unção de Deus",
      "Elaine Martins - Santificação",
      "Elia Oliveira - Te Adorarei",
      "Elevation - Praise (Louve)",
      "Eli Soares - Aos Pés da Cruz",
      "Eli Soares - Casa de Deus",
      "Eli Soares - Deus Cuida de Mim",
      "Eli Soares - Deus Forte",
      "Eli Soares - Ele É",
      "Eli Soares - Ele é Exaltado",
      "Eli Soares - Grande é o Senhor",
      "Eli Soares - Jeová é o Teu Cavaleiro",
      "Eli Soares - Os Anjos te Louvam",
      "Eli Soares - Porque Ele Vive",
      "Eli Soares - Santo, Santo, Santo",
      "Eli Soares - Se Eu Cair",
      "Eli Soares - Tu És Soberano",
      "Eli Soares - Tudo Que Eu Sou",
      "Eli Soares - Vem Com Josué Lutar em Jericó",
      "Eliezer e Marcelo - Dependente",
      "Emaus Music - Medley Digno de Tudo",
      "Emaus Music - Refúgio",
      "Ericka Nascimento - Vida Aos Sepulcros",
      "Esther Fiuax - Adoração Exclusiva",
      "Eyshila + Midian Lima - Medley Posso Clamar",
      "Eyshila - Nada Pode Calar Um Adorador",
      "Eyshila - O Milagre Sou Eu",
      "Fabiana Anastácio - Sou Eu",
      "Felipe Rodrigues + Marcus Salles - Amo o Senhor",
      "Felipe Rodrigues - Aclame ao Senhor",
      "Felipe Rodrigues - Até Que o Senhor Venha",
      "Felipe Rodrigues - Digno é o Senhor",
      "Felipe Rodrigues - Eu Sou do Meu Amado",
      "Felipe Rodrigues - Eu Sou Teu",
      "Felipe Rodrigues - Fiel é Deus",
      "Felipe Rodrigues - Melhor Lugar",
      "Felipe Rodrigues - Primeira Essência",
      "Felipe Rodrigues - Tudo é Perda",
      "Fernanda Brum - Amo o Senhor",
      "Fernanda Brum - Apenas Um Toque",
      "Fernanda Brum - Há Liberdade",
      "Fernanda Brum - O Que Sua Glória Fez Comigo",
      "Fernanda Brum - Onde o Fogo Não Apaga",
      "Fernanda Brum - Puro Nardo",
      "Fernanda Brum - Redenção",
      "Fernanda Brum - Tua Glória",
      "Fernanda Brum - Yeshua",
      "Fernanda Madaloni - Canção do Apocalipse",
      "Fernanda Madaloni - Medley",
      "Fernanda Madaloni - Porque Ele Vive",
      "Fernandinho - A Alegria do Senhor",
      "Fernandinho - Agindo Deus",
      "Fernandinho - Alvo Mais Que a Neve",
      "Fernandinho - Cidade Santa",
      "Fernandinho - Dançar Na Chuva",
      "Fernandinho - Deus Não Está Morto",
      "Fernandinho - Eis Que Estou à Porta",
      "Fernandinho - Faz Chover",
      "Fernandinho - Grandes Coisas",
      "Fernandinho - Há Um Rio",
      "Fernandinho - Jesus, Filho de Deus",
      "Fernandinho - Medley Seu Sangue",
      "Fernandinho - Mil Cairão",
      "Fernandinho - Nada Além do Sangue",
      "Fernandinho - Não Mais Escravos",
      "Fernandinho - O Hino",
      "Fernandinho - Os Que Confiam",
      "Fernandinho - Os Teus Sonhos",
      "Fernandinho - Resiliência",
      "Fernandinho - Se Não For Pra Ti Adorar",
      "Fernandinho - Seu Sangue",
      "Fernandinho - Sou Feliz",
      "Fernandinho - Todas As Coisas",
      "Fernandinho - Tu És Fiel",
      "Fernandinho - Um Dia em Tua Casa",
      "Fernandinho - Uma Coisa Peço Ao Senhor",
      "Fernandinho - Uma Nova História (Acústico)",
      "Fernandinho - Venha o Teu Reino",
      "Fernandinho - Yeshua",
      "Fhop Music - A Boa Parte",
      "Fhop Music - Bendito é o Rei",
      "Fhop Music - Canção Eterna",
      "Fhop Music - Colossenses e Suas Linhas de Amor",
      "Fhop Music - Gratidão",
      "Fhop Music - Há Poder",
      "Fhop Music - Indesculpável",
      "Fhop Music - Meia Noite",
      "Fhop Music - Sublime",
      "Fhop Music - Tu És + Águas Purificadoras",
      "Fhop Music - Uma Vez",
      "Fhop Music - Único",
      "Fhop Music - Único 2.0",
      "Gabi Sampaio - Ambição",
      "Gabi Sampaio - Medley Eu Vou Construir",
      "Gabriel Guedes - A Benção",
      "Gabriel Guedes - Canta Minh'Alma",
      "Gabriel Guedes - Ele Vem",
      "Gabriel Guedes - In Memoriam",
      "Gabriel Guedes - Nada Mais",
      "Gabriel Guedes - Santo Pra Sempre",
      "Gabriel Guedes - Vitorioso És",
      "Gabriel Guedes - Vitorioso És, És o Amor",
      "Gabriela Rocha + Fernandinho - Creio Em Ti",
      "Gabriela Rocha - A Ele a Glória + Porque Ele Vive",
      "Gabriela Rocha - Agnus Dei",
      "Gabriela Rocha - Atos 2",
      "Gabriela Rocha - Creio Que Tu És a Cura",
      "Gabriela Rocha - Deus Está Aqui",
      "Gabriela Rocha - Espírito Enche Minha Vida",
      "Gabriela Rocha - Eu Navegarei",
      "Gabriela Rocha - Eu Sou Teu",
      "Gabriela Rocha - Eu Sou Teu 2.0",
      "Gabriela Rocha - Leão",
      "Gabriela Rocha - Lugar Secreto",
      "Gabriela Rocha - Me Atraiu",
      "Gabriela Rocha - Medley Meu Coração é Teu",
      "Gabriela Rocha - Medley Meu Respirar",
      "Gabriela Rocha - Medley Nada Além de Ti",
      "Gabriela Rocha - Medley Poderoso Deus",
      "Gabriela Rocha - Medley Senhor Formoso És",
      "Gabriela Rocha - Medley Tofreu Gerando Salvação",
      "Gabriela Rocha - Pra Onde Iremos",
      "Gabriela Rocha - Teu Santo Nome",
      "Gabriela Rocha - Teu Santo Nome 2.0",
      "Gabriela Rocha - Toda Terra",
      "Gabriela Rocha - Vida Aos Sepulcros",
      "Gabriela Rocha - Vida Aos Sepulcros (Edit)",
      "Gerson Rufino - Eu Só Quero Adorar",
      "Get Worship - Derrama o Meu Perfume",
      "Get Worship - Senhor, Tu És Bom",
      "Get Worship - Uma Carta Viva",
      "Get Worship - Um Novo Dia",
      "Gézi Monteiro - Medley Meu Prazer",
      "Guilherme Baptista - Medley Te Louvarei",
      "Heloísa Rosa - Estou Livre",
      "Heloísa Rosa - Há Um Lugar",
      "Heloísa Rosa - Jesus é o Caminho",
      "IBAB - Bondade de Deus",
      "IBAB - Canta Minh'Alma",
      "IBAB - Eu Me Rendo",
      "IBAB - Me Derramar",
      "IBAB - Medley Tributo Yeovah",
      "Igor Zolla - Atrai O Meu Coração",
      "Thomas Serra - Furioso Oceano",
      "Ipalpha - Ao Pé da Cruz",
      "Ipalpha - És o Rei Que Vem",
      "Ipalpha - Vinho e Pão",
      "Isaías Saad - Enche-me",
      "Isaías Saad - Medley Águas Purificadoras",
      "Isaías Saad - Medley Ruja o Leão",
      "Isaías Saad - Ousado Amor",
      "Isaías Saad - Senhor dos Exércitos",
      "Isadora Pompeo - Bençãos Que Não Têm Fim",
      "Isadora Pompeo - Minha Alma Te Ama",
      "Israel Nogueira - Medley Pode Morar Aqui",
      "Israel Salazar - Barulho de Festa",
      "Israel Salazar - Canção Ao Cordeiro",
      "Israel Salazar - Graça",
      "Israel Salazar - No Meio dos Louvores",
      "Jefferson e Suellen - Acende Outra Vez",
      "Jefferson e Suellen - Cordeiro e Leão",
      "Jefferson e Suellen - Ele Reina",
      "Jefferson e Suellen - Ele Vem",
      "Jefferson e Suellen - Foi Na Cruz",
      "Jefferson e Suellen - Labareda",
      "Jefferson e Suellen - Vem Me Buscar",
      "Josué Freitas - Medley João 20",
      "Juliano Son - Eu Vou Construir",
      "Juliano Son - Milagres",
      "Julliany Souza - Canção Que Não Envelhece",
      "Julliany Souza - Colossenses 1",
      "Julliany Souza - Deus é Quem Me Fortalece",
      "Julliany Souza - Leão de Judá",
      "Julliany Souza - Lindo Momento",
      "Julliany Souza - Quem é Esse",
      "Júlia Vitória - Além do Rio Azul",
      "Júlia Vitória - Canção dos Redimidos",
      "Júlia Vitória - De Dentro Pra Fora",
      "Júlia Vitória - João Viu + Além do Rio Azul",
      "Júlia Vitória - Nós Te Adoramos",
      "Júlia Vitória - Som das Águas",
      "KF - Estamos de Pé",
      "Kailane Frauches - Eu Vou Fazer",
      "Kailane Frauches - Passa Lá em Casa Jesus",
      "Kailane Frauches - Remanescentes",
      "Kaleb e Josh - Aviva-nos Medley",
      "Kemilly Santos - Deus de Obras Completas",
      "Kemilly Santos - Resistência",
      "Kemuel - Algo Novo",
      "Kemuel - Oh Quão Lindo Esse Nome É",
      "Kleber Lucas - Eu Vou Seguir Com Fé",
      "Kleber Lucas - Meu Alvo é Cristo",
      "Kleber Lucas - Pra Valer a Pena",
      "Kleber Lucas - Te Agradeço",
      "Lagoinha Worship - Grato Sou",
      "Lauriete - Igual Não Há",
      "Lauriete - Palavras",
      "Leandro Borges - Medley Clássicos",
      "Leonardo Gonçalves - Getsemani",
      "Livres Para Adorar - Mais Forte Que a Morte",
      "Livres Para Adorar - Quando o Mundo Cai ao Meu Redor",
      "Livres Para Adorar - Vai Valer a Pena",
      "Louvor Aliança - Medley Igreja Pequena",
      "Ludmila Ferber - Nunca Pare de Lutar",
      "Ludmila Ferber - Os Sonhos de Deus",
      "Lukas Agustinho - Medley Escudo",
      "Lukas Agustinho - Medley Sião",
      "Luma Elpídio - Liberta-me de Mim",
      "Marcelo Markes - Além do Impossível",
      "Marcelo Markes - Eu Tenho Você",
      "Marcelo Markes - Messias",
      "Marcelo Markes - Sinto Fluir",
      "Marcus Salles - Cordeiro e o Leão",
      "Marcus Salles - Estamos de Pé",
      "Marcus Salles - Medley Até Que Ele Venha",
      "Marcus Salles - Ruja o Leão",
      "Marcus Salles - Teu Amor Não Falha",
      "Marcus Salles - Vim para Adorar-Te",
      "Maria Marçal - Deixa",
      "Marine Friesen - Alfa e Ômega",
      "Marine Friesen - Óleo de Alegria",
      "Marquinho Gomes - Não Há Deus Maior",
      "Mateus Brito - Medley Ruja o Leão",
      "Midian Lima - Jó",
      "Midian Lima - Olharei Pro Alto",
      "Ministério Apascentar - Deus do Impossível",
      "Ministério Apascentar - Restitui",
      "Ministério Apascentar - Toque No Altar",
      "Ministério Avivah - Maranata",
      "Ministério Avivah - Pra Sempre",
      "Ministério Cristo Vivo - Teu Reino",
      "Ministério Ipiranga - Ressuscita",
      "Ministério Ipiranga - Última Chance",
      "Ministério Sarando a Terra - Deus do Secreto",
      "Ministério Toque No Altar - Aleluia Hosana",
      "Ministério Trazendo a Arca - Celebre",
      "Ministério Trazendo a Arca - Entre a Fé e a Razão",
      "Ministério Trazendo a Arca - Lembra Senhor",
      "Ministério Trazendo a Arca - Marca da Promessa",
      "Ministério Trazendo a Arca - O Chão Vai Tremer",
      "Ministério Trazendo a Arca - Olha Pra Mim",
      "Ministério Trazendo a Arca - Senhor e Rei",
      "Ministério Trazendo a Arca - Serás Sempre Deus",
      "Ministério Trazendo a Arca - Sobre As Águas",
      "Ministério Trazendo a Arca - Sobre As Águas 2.0",
      "Ministério Trazendo a Arca - Te Louvarei",
      "Ministério Trazendo a Arca - Trazendo a Arca",
      "Ministério Zoe - Aquieta Minh'Alma",
      "Minist. Toque No Altar - Eu Vou Viver Uma Virada",
      "Morada - Emaús",
      "Morada - É Tudo Sobre Você",
      "Morada - Medley Em Espírito",
      "Morada - Medley Eu Te Agradeço",
      "Morada - Medley Leão de Judá",
      "Morada - Medley Sonda-me",
      "Morada - Medley Tu és Santo",
      "Morada - Pra Onde Eu Irei",
      "Morada - Só Tu És Santo",
      "Nazarenos - O Grande Eu Sou",
      "Nívea Soares & Ítalo Gonçalves - Em Tua Presença",
      "Nívea Soares - Enche Este Lugar",
      "Nívea Soares - Eu Vou Construir",
      "Nívea Soares - Filho do Deus Vivo",
      "Nívea Soares - Maravilhado",
      "Nívea Soares - Não Seremos Abalados",
      "Nívea Soares - Que Se Abram os Céus",
      "Nívea Soares - Quem é Como o Nosso Deus",
      "Nívea Soares - Rio",
      "Nívea Soares - Tempo de Adorar",
      "Nívea Soares - Teu Amor Não Falha",
      "Nívea Soares - Um Só",
      "Novo Canto + Julliany Souza - Colossenses 1",
      "O Canto das Igrejas - Tu És Deus",
      "Oficina G3 - Ele Vive",
      "Oficina G3 - Incondicional",
      "One Voice - Medley Santo Pra Sempre",
      "Paloma Possi - Santo dos Santos",
      "Paulo César Baruk - Agradeço",
      "Paulo César Baruk - Cantarei Teu Amor",
      "Paulo César Baruk - Clamo Jesus",
      "Paulo César Baruk - Ele Continua Sendo Bom",
      "Paulo César Baruk - Em Teus Braços",
      "Paulo César Baruk - Jesus Em Tua Presença",
      "Paulo César Baruk - Me Atraiu",
      "Paulo César Baruk - Reina Em Mim",
      "Paulo César Baruk - Santo Espírito",
      "Paulo César Baruk - Sossegai",
      "Paulo César Baruk - Te Agradeço",
      "Pedras Vivas - Ó Noite Santa",
      "Pedras Vivas - Pai Nosso",
      "Pedro Henrique - Só Tu És Santo",
      "Peter Quintino - O Nosso General é Cristo",
      "Produção Elite - Medley Eu Quero é Deus",
      "Projeto Sola - Até Outra Vez",
      "Quatro Por Um - Diante de Ti",
      "Rachael Novaes - Tudo O Que Eu Mais Quero",
      "Raiz Coral - A Coroa",
      "Raiz Worship - Vencendo Vem Jesus",
      "Rapha Gonçalves - Sobre as Águas",
      "Rebeca Carvalho - Ele Me Ama",
      "Renascer Praise - Escape",
      "Renascer Praise - Eu Vou Clamar",
      "Renascer Praise - Há Um Lugar",
      "Renascer Praise - Hosana",
      "Renascer Praise - Jesus o Plano Perfeito",
      "Renascer Praise - Mil Graus",
      "Renascer Praise - Novo Dia, Novo Tempo",
      "Renascer Praise - Pelo Sangue",
      "Renascer Praise - Santo, Santo, Santo",
      "Renascer Praise - Ser Conhecido de Deus",
      "Ronaldo Bezerra - Tu És Santo",
      "Sala do Groove - Me Faz Viver",
      "Samuel Dias - Como Flecha",
      "Samuel Messias - A Glória Desta Última Casa",
      "Samuel Messias - Eu Não Perdi o Controle",
      "Samuel Messias - Os Planos de Deus",
      "Samuel Messias - Toda Via Me Alegrarei",
      "Samuel Tayrone - Que Presença é Essa",
      "Sara Evelyn - Um Pouco Mais",
      "Sara Oliveira - Caia Fogo",
      "Sarah Beatriz - O Maior Vilão Sou Eu",
      "Sarah Beatriz - O Poder do Teu Amor",
      "Sarah Beatriz - Toda Via Me Alegrarei",
      "Sarah Farias - Deixa Eu Te Usar",
      "Sarah Farias - O Rosto de Cristo",
      "Sarah Farias - Se Eu Não Te Ouvir",
      "Sarah Oliveira - Cadeias Quebrar",
      "Sérgio Lopes - Tente Lembrar",
      "Shirley Carvalhaes + Anderson Freire - Vendavais",
      "Soraya Moraes - Cadeias Quebrar",
      "Soraya Moraes - Caminho No Deserto",
      "Soraya Moraes - Quão Grande é o Meu Deus",
      "Stella Laura - O Senhor é o Meu Pastor",
      "Sued Silva - Na Fenda da Rocha",
      "Sued Silva - O Nome Dele é Jesus",
      "Sued Silva - Reacende a Chama",
      "Thalles Roberto - A Resposta",
      "Thalles Roberto - Arde Outra Vez",
      "Thalles Roberto - Com Muito Louvor",
      "Thalles Roberto - Desapareceu Um Povo",
      "Thalles Roberto - Deus da Minha Vida",
      "Thalles Roberto - Me Faz Viver",
      "Thamires Garcia - A Tua Mesa Cura",
      "Theo Rubia + Fernandinho - Ninguém Pode Parar",
      "Theo Rubia - Eu Só Quero Tua Presença",
      "Theo Rubia - Medley Nada Além do Sangue",
      "Theo Rubia - Um Milhão de Anos",
      "Toque No Altar - Leva-me Além",
      "Trazendo a Arca - Meu Melhor",
      "Valesca Mayssa - Boa Obra",
      "Valesca Mayssa - Eis-me Aqui",
      "Valesca Mayssa - Eu Sou Teu Pai",
      "Valesca Mayssa - Inflama",
      "Valesca Mayssa - Medley Dias de Guerra",
      "Valesca Mayssa - O Encontro",
      "Vigília dos Asafes - Poder Pra Salvar",
      "Vineyard - Entrega",
      "Vineyard - Meu Respirar",
      "Vineyard - Quebrantado",
      "Vineyard - Reina Em Mim",
      "Vineyard - Santo",
      "Vineyard - Senhor, Te Quero",
      "Vineyard - Vem, Está é a Hora",
      "Vineyard - Vim Para Adorar-te",
      "Wesley Santos - Cantai ao Senhor",
      "Wesley Santos - Grandioso És Tu",
      "Wesley Santos - O Rei Está Voltando",
      "Yasmim Versão Elite - O Fogo Arderá"
    ]
  },
  {
    producer: "alagoa",
    source: "Acervo Alagoa",
    tracks: [
      "Adhemar de Campos - Grande é o Senhor",
      "Alice Maciel - Sua Presença",
      "Aline Barros - Primeira Essência (Ao Vivo)",
      "Aline Barros - Casa do Pai",
      "Aline Barros - Digno é o Senhor",
      "Aline Barros - Imensurável",
      "Aline Barros - Jeová Jireh",
      "Aline Barros - Para Sempre Te Adorarei",
      "Aline Barros - Recomeçar",
      "Aline Barros - Santidade",
      "Aline Barros - Sou Mais Que Vencedor",
      "Aline Barros - Soube Que Me Amavas",
      "Aline Barros e Fernandinho - Rendido Estou",
      "Anderson Freire - A Glória é Tua",
      "Anderson Freire - A Igreja Vem",
      "Anderson Freire - Canção do Céu",
      "Anderson Freire - Igual Não Há",
      "Anderson Freire e Bruna Karla - Identidade",
      "Anderson Freire - Efésios 6",
      "Anderson Freire feat. Gisele Nascimento - O Mapa do Tesouro (Ao Vivo)",
      "Andréa Fontes - João Viu (Ao Vivo)",
      "Arianne - Deserto",
      "Avivah - Maranata",
      "Brás Adoração - Vem Cantar Louvores",
      "Bruna Karla - Força",
      "Bruna Karla - Pai, Eu Confiarei",
      "Canção e Louvor - Dependente",
      "Canção e Louvor - Eu Quero Mais",
      "Canção e Louvor - Eu Sou Mistério",
      "Canção e Louvor - O Céu Desceu",
      "Canção e Louvor - Rei e Santo",
      "Canção e Louvor - Salmo 24",
      "Cassiane - Amigo Espírito Santo",
      "Cassiane - Lugar da Tua Presença",
      "Cassiane - Não Abro Mão",
      "Cassiane - O Leão e o Cordeiro",
      "Cassiane - O Segredo",
      "Cassiane - O Todo-Poderoso",
      "Cassiane - Tremendo e Santo",
      "Cassiane - Vou Seguir",
      "Cassiane e Gabriela Rocha - Minha Bênção (Ao Vivo)",
      "Cassiane feat. Fernanda Brum - Imagine (Ao Vivo)",
      "Chagas Sobrinho - É Como um Sonho",
      "Charles Ben - Eu Me Rendo",
      "Cícero Oliveira - Quem Tem Jesus Tem Tudo",
      "Comunidade Zona Sul - O Nosso General é Cristo",
      "Coral Resgate - Envolve-me",
      "Cristina Mel - Jerusalém e Eu",
      "Damares - Consolador",
      "Damares - Sacrifício e Adoração",
      "Danielle Cristina - Deus Tu És Santo",
      "Diante do Trono - Preciso de Ti (Ao Vivo)",
      "Elaine de Jesus - Quem Chora Pra Deus",
      "Elaine Martins - Santificação",
      "Eli Soares, Álvaro Tito - Não Há Barreiras",
      "Eliã Oliveira - No Tempo D’Ele",
      "Eliã Oliveira - O Céu em Ação",
      "Eliã Oliveira - Salmos 91",
      "Eliane Fernandes - Presença",
      "Eliane Fernandes - Vai Passar",
      "Esteves Jacinto - Oração e Vitória",
      "Eyshila - Casa de Bênção",
      "Eyshila - Fiel a Mim",
      "Fabiana Anastácio - Adorarei",
      "Fabiana Anastácio - Sou Eu",
      "Fernanda Brum - A Visão da Glória",
      "Fernanda Brum - Amo o Senhor",
      "Fernanda Brum - Cura-me",
      "Fernanda Brum - Eu Vejo a Glória",
      "Fernanda Brum - Eu Vou",
      "Fernanda Brum - O Que Tua Glória Fez Comigo",
      "Fernanda Brum - Onde o Fogo Não Apaga",
      "Fernanda Brum - Santo (Holy)",
      "Fernandinho - Moisés",
      "Fernandinho Moises EDIT FINAL",
      "Fernandinho - Os Que Confiam",
      "Fernandinho - Único",
      "Gabriela Rocha - Hino da Vitória",
      "Gabriela Rocha - Me Atraiu",
      "Gabriela Rocha, Jéssica Augusto - Canção do Céu",
      "Gerson Rufino - Eu Só Quero Adorar",
      "Gerson Rufino - Vai Passar",
      "Grande Coral da UMADEB - Medley",
      "IBAB Celebração - Bondade de Deus",
      "Isaías Saad - Bondade de Deus",
      "Isaías Saad + Nívea Soares - Ruja o Leão / Que Se Abram os Céus",
      "Israel Nogueira - Oferta Agradável a Ti",
      "Israel Salazar - No Meio dos Louvores",
      "Jairo Bonfim - Ressurreto",
      "Jefferson e Suellen - Ele Reina",
      "Jefferson e Suellen - Jesus no Barco",
      "Jefferson e Suellen - Labareda",
      "Jéssica Augusto - A Última Palavra é Dele",
      "Jozyanne - Abra os Meus Olhos",
      "Jozyanne e Cassiane - Santidade",
      "Jozyanne e Midian Lima - Sinto o Teu Poder",
      "Jozyanne, Midian Lima, Nathália Braga e Pedro Henrique - Meu Milagre",
      "Kailane Frauches - Era a Mão de Deus",
      "Kailane Frauches - Passa Lá em Casa Jesus",
      "Kellen Byanca - Está Tudo Bem",
      "Kellen Byanca e Jessé Aguiar - Por Causa Dele",
      "Kemilly Santos, Damares - Se o Mar Não Se Abrir, Firme nas Promessas",
      "Larissa Pires - A Tua Palavra",
      "Lauriete - Deus dos Deuses",
      "Lauriete - Igual Não Há",
      "Lauriete - João Viu",
      "Leandro Borges - O Rei Está Voltando",
      "Lukas Agustinho - O Escudo + Sou Um Milagre",
      "Lukas Agustinho, Samuel Messias, Eliezer de Tarsis - Louve",
      "Marcus Salles - Estamos de Pé",
      "Maria Marçal - Deixa",
      "Maria Marçal - Uma Coisa Nova",
      "Mariana Aguiar - Porque Ele Vive",
      "Marine Friesen - Santo Pra Sempre",
      "Medley - Arrebatamento",
      "Medley - João 20",
      "Michele Nascimento - Louve e Adore",
      "Michele Nascimento - Portões Celestiais",
      "Midian Lima - Medley Corinhos de Fogo",
      "Midian Lima - Não Pare (10K)",
      "Midian Lima - Prioridade",
      "Midian Lima - Shekinah",
      "Midian Lima - Tu És Adorado",
      "Ministério Hebrom - Rendição",
      "Ministério Sarando a Terra Ferida - O Novo de Deus",
      "Morada - Jesus em Tua Presença",
      "Nívea Soares - Nenhum Deus Como Tu (Ao Vivo)",
      "Paulo César Baruk - Oh Glória",
      "Pedro Henrique - Posso Clamar",
      "Quatro Por Um - Cinco Pães e Dois Peixinhos",
      "Rachael Novaes e Paulo César Baruk - O Amor de Deus",
      "Rayanne Vanessa - Comandante Supremo",
      "Rayanne Vanessa - Eu Cuido",
      "Rayanne Vanessa - Imutável",
      "Rayanne Vanessa - Quem Me Vê Cantando",
      "Rayssa e Ravel - Consolador",
      "Renascer Praise - Escape",
      "Renascer Praise - Jesus, o Plano Perfeito",
      "Rose Nascimento - Lázaro, o Amigo Especial",
      "Ruthe Dayanne feat. Eliã Oliveira - O Grande é Ele",
      "Samuel Mariano - Deus Escrevendo",
      "Samuel Messias - Os Planos de Deus",
      "Samuel Messias - Você Não Vai Parar",
      "Sandra Pires - Poderosamente Vivo",
      "Sara Evelyn - Vem Senhor",
      "Sarah Beatriz - Eu Creio",
      "Sarah Farias - Deixa Eu Te Usar",
      "Sarah Farias - O Rosto de Cristo",
      "Sarah Farias - Se Eu Não Te Ouvir",
      "Sarah Farias - Sobrevivi",
      "Shirley Carvalhaes - Deus Tremendo",
      "Shirley Carvalhaes - Faraó ou Deus",
      "Shirley Carvalhaes - Vendavais",
      "Shirley Carvalhaes - Acima das Estrelas",
      "Som e Louvor - Corinhos 6: Festa de Crente",
      "Som e Louvor - Vem com Josué",
      "Som e Louvor e Stella Laura - Quem Viver Verá",
      "Soraya Moraes - Caminho no Deserto",
      "SoulLivre e Kemuel - Não Mais Escravos",
      "Stella Laura - Vem Senhor",
      "Stella Laura, Sara Evelyn e Carol Tauber - Vem Senhor",
      "Sued Silva - Existe Vida Aí",
      "Sued Silva - O Nome DEle",
      "Trio Nascimento - Chegou o Avivamento",
      "Trio Nascimento - Medley",
      "Valesca Mayssa - Boa Obra",
      "Valesca Mayssa - Dia Após Dia",
      "Valesca Mayssa - Eis-me Aqui",
      "Valesca Mayssa - Eu Sou Teu Pai",
      "Valesca Mayssa e Stella Laura - Dias de Guerra",
      "Vanessa Carvalho - Cicatrizes",
      "Vanilda Bordieri - Na Tua Presença",
      "Vitória Souza - Livramento",
      "Voz da Verdade - Além do Rio Azul",
      "Voz da Verdade - O Escudo",
      "Voz da Verdade - Sou um Milagre (Ao Vivo)",
      "Weslei Santos - Maranata"
    ]
  }
];
